service: ai-file-summarizer-app

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  pre-sign:
    handler: pre-sign/handler.handler
    package:
      include:
        - pre-sign/**
      individually: true
    events:
      - http:
          path: pre-sign
          method: post
          cors: true

  summarize:
    handler: summarize/summarize.handler
    package:
      include:
        - summarize/**
      individually: true
    events:
      - http:
          path: summarize
          method: post
          cors: true
